# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShopList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Database'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'FirebaseAnalytics', '6.1.3'

pod 'SwipeCellKit'
pod "KRProgressHUD"

  # Pods for ShopList

end
